# Generated by Django 5.2.1 on 2025-05-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_ch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='contabilization',
            field=models.BooleanField(default=False),
        ),
    ]
