# Generated by Django 5.2.1 on 2025-05-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_ch', '0002_activitysubmission_contabilization'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='type',
            field=models.CharField(choices=[('WORKSHOP', 'Workshop'), ('PALESTRA', 'Palestra'), ('CURSO', 'Curso')], default='WORKSHOP', max_length=10),
        ),
    ]
