# Generated by Django 5.2.1 on 2025-05-28 03:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_ch', '0003_activitysubmission_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitysubmission',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='activitysubmission',
            old_name='reviewed_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
