# Generated by Django 5.2.1 on 2025-05-28 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_ch', '0004_rename_submitted_at_activitysubmission_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitysubmission',
            old_name='updated_at',
            new_name='reviewed_at',
        ),
        migrations.RenameField(
            model_name='activitysubmission',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
    ]
